results_dir: '/home/scratch.p3/sean/tlt3_experiments/imagenet/tf2_byom_res18'
train_config:
  train_dataset_path: '/home/projects2_metropolis/datasets/public/imagenet2012/val_yuw'
  val_dataset_path: '/home/projects2_metropolis/datasets/public/imagenet2012/val_yuw'
  pretrained_model_path: ''
  batch_size_per_gpu: 64
  preprocess_mode: 'torch'
  n_epochs: 80
eval_config:
  eval_dataset_path: '/home/projects2_metropolis/datasets/public/imagenet2012/val_yuw'
  model_path: '/home/projects2_metropolis/tmp/sean/converted_models_classification/convnext_tiny/convnext_tiny.tltb'
  top_k: 1
  batch_size: 64
  n_workers: 10
key: 'nvidia_tlt'
data_format: 'channels_first'
