
results_dir: '/home/binz/tao-tf2/results_enb0_16bit'
train:
  train_dataset_path: '/home/binz/tao-tf2/dataset/target_chips'
  val_dataset_path: '/home/binz/tao-tf2/dataset/target_chips'
  pretrained_model_path: ''
  batch_size_per_gpu: 4
  n_epochs: 3
  image_mean: [7834.4968]

eval:
  eval_dataset_path: '/home/binz/tao-tf2/dataset/target_chips'
  # model_path: '/home/binz/Tao/tao-tf2/results/weights/resnet18_bn_001.eff'
  model_path: '/home/binz/tao-tf2/results_enb0_16bit/weights/efficientnet-b0_010.eff'
  top_k: 1
  batch_size: 2
  n_workers: 0
model:
  arch: 'efficientnet_b0'
  # arch: 'resnet'
  # n_layers: 18
  input_image_size: [1,640,640]
  input_image_depth: 16
key: 'nvidia_tlt'
data_format: 'channels_last'