# train 16 bit images with efficientnet-b0
results_dir: '/home/binz/tao-tf2/results_enb0_16bit'
encryption_key: nvidia_tlt
dataset:
  train_dataset_path: '/home/binz/tao-tf2/dataset/target_chips'
  val_dataset_path: '/home/binz/tao-tf2/dataset/target_chips'
  image_mean: [7834.4968]
  preprocess_mode: 'caffe'
  augmentation:
    enable_random_crop: True
train:
  qat: False
  # checkpoint: '/home/binz/Tao/tao-tf2/results_enb0_16bit_train/weights/efficientnet-b0_004_prune.tlt'
  batch_size_per_gpu: 4
  num_epochs: 3
model:
  backbone: 'efficientnet-b0'
  input_image_depth: 16

