results_dir: '/home/scratch.p3/yuw/tlt3_experiments/tf2-effdet-d4'
data_config:
  training_file_pattern: '/home/scratch.p3/yuw/datasets/coco/train-*'
  validation_file_pattern: '/home/scratch.p3/yuw/datasets/coco/val-*'
  validation_json_file: '/home/scratch.p3/yuw/datasets/coco/annotations/instances_val2017.json'
train_config:
  amp: True
  num_examples_per_epoch: 120000
  train_batch_size: 16
  checkpoint_period: 1
inference_config:
  output_dir: '/home/scratch.p3/yuw/tlt3_experiments/tf2-effdet-d4/inference_output'
  model_path: '/home/scratch.p3/yuw/tlt3_experiments/tf2-effdet-d4/weights/efficientdet-d0_070.eff'
  # model_path: '/home/scratch.p3/yuw/tlt3_experiments/tf2-effdet-d4/weights/export/efficientdet-d0_070.fp32.engine'
  # model_path: '/home/scratch.p3/yuw/tlt3_experiments/tf2-effdet-d2/ema_weights/emackpt-90'
  # model_path: '/home/scratch.p3/yuw/tlt3_experiments/tf2-effdet-d2/ema_weights/export/emackpt-90.int8.engine'
  image_dir: '/home/scratch.p3/yuw/datasets/coco/raw-data/val2017'
  batch_size: 4
