data:
  train_tfrecords:
    - '/home/scratch.p3/yuw/datasets/coco/train-*'
  val_tfrecords:
    - '/home/scratch.p3/yuw/datasets/coco/val-*'
  val_json_file: '/home/scratch.p3/yuw/datasets/coco/annotations/instances_val2017.json'
train:
  amp: True
  checkpoint: "/home/scratch.p3/yuw/tlt3_experiments/nvimagenet/tf2_effnet_b0/weights/efficientnet_b0_300"
  num_examples_per_epoch: 120000
  batch_size: 16
  checkpoint_period: 5
  results_dir: '/home/scratch.p3/yuw/tlt3_experiments/tf2-effdet-d0'
evaluate:
  batch_size: 16
  num_samples: 500
