results_dir: '/home/binz/tao-tf2/results_enb0'
train:
  train_dataset_path: '/home/binz/tao-tf2/dataset/flower_17/train'
  val_dataset_path: '/home/binz/tao-tf2/dataset/flower_17/validation'
  pretrained_model_path: ''
  batch_size_per_gpu: 16
  n_epochs: 3

eval:
  eval_dataset_path: '/home/binz/tao-tf2/dataset/flower_17/validation'
  # model_path: '/home/binz/Tao/tao-tf2/results/weights/resnet18_bn_001.eff'
  model_path: '/home/binz/tao-tf2/results_enb0/weights/efficientnet-b0_010.eff'
  top_k: 1
  batch_size: 16
  n_workers: 0
model:
  arch: 'efficientnet_b0'
  # arch: 'resnet'
  # n_layers: 18
  input_image_size: [3,500,500]
  input_image_depth: 8
key: 'nvidia_tlt'
data_format: 'channels_last'